#!/bin/sh
#
#-----------------------------------------------------------------------

cp -n .Xdefaults.em  ~/.Xdefaults.em
cp -n .Xdefaults.xe  ~/.Xdefaults.xe

#-----------------------------------------------------------------------

SCRIPT_PATH=$(dirname $(readlink -f $0))     

SCRIPT_PATH="`( cd \"$SCRIPT_PATH\" && pwd )`"  # absolutized and normalized

#-----------------------------------------------------------------------

ln -f -s $SCRIPT_PATH/xemacs ~/.xemacs

#-----------------------------------------------------------------------



